create table "CABIN_USER_APPOINTMENT"
(
    "USER_ID"         NUMBER(10) CONSTRAINT USER_ID_CABIN_FK REFERENCES USERS,
    "CABIN_ID" NUMBER(10) CONSTRAINT  CABIN_ID_CABIN_FK REFERENCES CABIN,
    "ENTRY_DATE"           DATE    not null,
    "EXIT_DATE"      DATE not null

);