create table "DOCTOR_SCHEDULE"
(
    "DOCTOR_ID" NUMBER(10) NOT NULL CONSTRAINT DOC_ID_PK PRIMARY KEY ,

    "SAT_START" number(10) ,
    "SAT_END" NUMBER(10),
    "SAT_MAX" NUMBER(10),

    "SUN_START" NUMBER(10),
    "SUN_END" NUMBER(10),
    "SUN_MAX" NUMBER(10),

    "MON_START" NUMBER(10),
    "MON_END" NUMBER(10),
    "MON_MAX" NUMBER(10),

    "TUES_START" NUMBER(10),
    "TUES_END" NUMBER(10),
    "TUES_MAX" NUMBER(10),

    "WED_START" NUMBER(10),
    "WED_END" NUMBER(10),
    "WED_MAX" NUMBER(10),

    "THU_START" NUMBER(10),
    "THU_END" NUMBER(10),
    "THU_MAX" NUMBER(10),

    "FRI_START" NUMBER(10),
    "FRI_END" NUMBER(10),
    "FRI_MAX" NUMBER(10)
);